### ISSUE TITLE
Shortcuts Conflict with Kee Password Manager Firefox Plugin

### ISSUE THREAD

**Issue by boolean-array** [gsomoza/firefox-easy-container-shortcuts#10]
Out of 4 containers, only the third one works. Num1 & num4 do not work because there is a conflict with the [KeePass plugin](https://addons.mozilla.org/en-US/firefox/addon/keefox/). I have no idea why 2 doesn't work. Then I removed all the containers and created them again and now nothing works.

**Comment by gsomoza** [comment]
Thanks for reporting! Unfortunately I can't think of any easy solutions to this conflict... so I'm afraid we might have to wait until Firefox provide a UI for re-mapping shortcuts.

Do you know what those shortcuts are used for in the Kee Password Manager plugin? Contacting them might also help.

**Comment by boolean-array** [comment]
Ctrl+Shift+4 shows a password generator popup. Ctrl+Shift+1 pulls up the plugin menu. If I disable Kee, all of your shortcuts work so I'll see what I can find out about that end of it.

Here's all of 'em:
Ctrl+Shift+1 - Show Kee popup panel
Ctrl+Shift+2 - Show matched logins or login to KeePass as applicable (KeePass must be running on your computer)
Ctrl+Shift+4 - Generate a new password
Ctrl+Shift+6 - Force detection of forms on this page

**Comment by boolean-array** [comment]
I found this discussion: https://forum.kee.pm/t/how-to-disable-shortcuts/578. The author seems reluctant to add the option to disable keyboard shortcuts.

**Comment by gsomoza** [comment]
I'm not sure there's much I can (personally) do to fix this. If someone can find a good solution please let us know here and feel free to submit a PR!

**Comment by boolean-array** [comment]
I'm not sure what's changed but the hotkeys have been working reliably (for me) for over a week. I can't tell you what happened but my problem no longer exists. Thanks for looking into it all the same.

**Comment by gsomoza** [comment]
Glad to hear that, thanks for following up!

**Comment by gsomoza** [comment]
FYI Firefox now supports mapping custom shortcuts! https://bug1303384.bmoattachments.org/attachment.cgi?id=9051647
