### ISSUE TITLE
More than 8 containers

### ISSUE THREAD

**Issue by Firesphere** [gsomoza/firefox-easy-container-shortcuts#12]
When you have more than 8 containers, container 9 doesn't work, and everything after that doesn't either.

Of course, opening a new container with number 10 is tricky, but I would expect 9 and 0 to work.

**Comment by gsomoza** [comment]
Hmm interesting, I'll review and debug asap, thanks for reporting!

**Comment by gsomoza** [comment]
Hmm, opening container 9 worked for me. Are you still able to duplicate the issue? Please make sure you don't have any extensions that might have overwritten that specific key combination.

**Comment by Firesphere** [comment]
I've switched to a Linux based machine, so I can't reproduce due to that...

**Comment by gsomoza** [comment]
What were you using before? Hopefully someone else can test that. Container number 10 is not configured to work with "0", that's something we might be able to fix.

**Comment by gsomoza** [comment]
Just tested it: the commands don't work with "0" for some reason.. that's probably why I didn't add it originally. I'll close this for now but contributions are always welcome.
