### ISSUE TITLE
override website shortcuts?

### ISSUE THREAD

**Issue by nbeaver** [gsomoza/firefox-easy-container-shortcuts#13]
Some websites override keyboard shortcuts like Ctrl-Shift-1.

For example, Google Sheets uses "Ctrl-Shift-1" for ["Format as decimal"](https://support.google.com/docs/answer/181110?co=GENIE.Platform%3DDesktop&hl=en) and Outlook webmail uses Ctrl-Shift-2 for ["Go to Calendar"](http://it.health.uci.edu/service-desk/OWA-Outlook-Calendar-Online-CheatSheet.asp).

It would be nice if this Webextension could override these shortcuts. I'm not sure if this is even possible with the [Webextensions API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands), but I thought I would ask anyway.

**Comment by gsomoza** [comment]
Based on my current understanding of the Webextension API this is not possible, but it's a good suggestion. 

I think it would be even better if there was a system where extensions could register commands with default keyboard mappings that could then be customised by the users themselves! I think there's an ongoing discussion about that somewhere...

**Comment by gsomoza** [comment]
FYI Firefox now supports mapping our commands to custom shortcuts! You can see how to do that here: https://bug1303384.bmoattachments.org/attachment.cgi?id=9051647

**Comment by nbeaver** [comment]
This bug is still present for me in Firefox 74.0 on both Ubuntu and Windows 10.

The "Manage Extension Shortcuts" handles conflicts between browser extensions. There is no mechanism I can see that allows overriding keyboard shortcuts on websites like Google Sheets or Outlook webmail. Those still take priority over browser extensions like this one.

**Comment by gsomoza** [comment]
Yes, those will always take priority.. What you could do with the tool I linked above is map our extension's shortcuts to something that doesn't affect your workflow.

For example you could map the default "Ctrl-Shift-1" command so that the new container is opened with "Alt-Shift-1" instead. That would leave "Ctrl-Shift-1" available for using with Google Sheets.
