### ISSUE TITLE
Ctrl + Alt + # shortcut doesn't work on AZERTY layout

### ISSUE THREAD

**Issue by Otiel** [gsomoza/firefox-easy-container-shortcuts#15]
The option to open the current tab on a specified container (<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>#</kbd>) doesn't work on an AZERTY layout, except when <kbd>#</kbd> = <kbd>1</kbd>.

I believe this is because the <kbd>Ctrl</kbd><kbd>Alt</kbd> modifier (which is equivalent to <kbd>Alt Gr</kbd>) is used to type the low-right characters (in green on the picture below) on the AZERTY layout:

![image](https://user-images.githubusercontent.com/3851902/76622106-206c6900-6531-11ea-80b9-12974493cd7b.png)

**Comment by gsomoza** [comment]
Thanks for reporting this! I guess adding SHIFT to the combo (to trigger the number) doesn't work either right?

This is why it would be great if Firefox allow users to map keyboard shortcuts to whichever commands they want.

**Comment by Otiel** [comment]
>I guess adding SHIFT to the combo (to trigger the number) doesn't work either right?

No, it doesn't change anything. But changing the shortcut to <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Shift</kbd><kbd>#</kbd> might work, as <kbd>Ctrl</kbd><kbd>Alt</kbd> doesn't trigger the alternative character when <kbd>Shift</kbd> is pressed.

**Comment by gsomoza** [comment]
If <kbd>Shift</kbd> doesn't work for you, I'm not sure how we could fix this. Firefox doesn't support specifying shortcuts to those symbols out of the box (AFAIK) and the <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Shift</kbd><kbd>#</kbd> alternative is not possible with their API either. They don't even support detecting the keyboard layout out of the box (it would have to be done via JS)...

I'll leave this ticket open in case anyone finds a good way to solve it.

**Comment by gsomoza** [comment]
Oh, looks like Firefox *does* allow mapping custom shortcuts now 👏: https://bug1303384.bmoattachments.org/attachment.cgi?id=9051647

Could you check if remapping using that feature helps you? At least it's a temporary workaround.

**Comment by Otiel** [comment]
By feature you mean the Shortkeys addon?

**Comment by gsomoza** [comment]
No, I mean using the steps shown in the video. It should take you to a screen where you can choose custom shortcuts for the various commands that our extension offers.

**Comment by Otiel** [comment]
Ah yes, my bad - I didn't know that this functionality is baked into Firefox.

It works!

I'm not able to choose <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Shift</kbd><kbd>#</kbd> as you said, but I've settled for <kbd>Shift</kbd><kbd>Alt</kbd><kbd>#</kbd>, perfect.

![image](https://user-images.githubusercontent.com/3851902/76632905-36375980-6544-11ea-9ab8-4c0c886c4414.png)

Thanks!

**Comment by gsomoza** [comment]
Glad this works! Thanks for closing.
