### ISSUE TITLE
Decontain shortcut

### ISSUE THREAD

**Issue by alexozer** [gsomoza/firefox-easy-container-shortcuts#17]
Hi, I really like this extension! Much better than manually switching with button clicks using other extensions. However one feature I miss is the ability to switch a tab to the "default container", or "decontain" it. A shortcut that might make sense for this would be ctrl+alt+0. Thoughts?

**Comment by gsomoza** [comment]
That's a great idea @alexozer, we could look into using `0` as a shortcut to "no container". I'll mark this as "help wanted".

**Comment by orthand** [comment]
Hey, is there currently the possibility to add the "no container" option (independent of the chosen number/shortcut)? Would love to have this option even if it's unmapped by default.

**Comment by gsomoza** [comment]
Hi @orthand, I'm a bit swamped right now with my family getting expanded so I'm afraid I can't get to it at the moment, but I'd be happy to review and merge a PR if you're interested in doing that!
