### ISSUE TITLE
add 'Reopen the current tab on the default container'

### ISSUE THREAD

**Issue by zanona** [gsomoza/firefox-easy-container-shortcuts#19]
I find myself often browsing on a tab under an assigned container but wanted to move that same tab into the default _(unassigned)_ container which is the space I use for general non-contextual navigation.

I believe it would be great to “jump-out” of the assigned container to the default one with a shortcut.

**Comment by gsomoza** [comment]
I agree this would be a great feature! There's already a ticket for it, and we're open to contributions on it, so feel free to do that if you have some spare time: https://github.com/gsomoza/firefox-easy-container-shortcuts/issues/17
