### ISSUE TITLE
Alternative shortcut for Windows

### ISSUE THREAD

**Issue by no-realm** [gsomoza/firefox-easy-container-shortcuts#3]
Hey,
really like this extension, my only minor problem is the shortcut for Windows (ctrl+shift+#).
Maybe it's a personal thing, but I personally prefer the shortcut that is used for macOS (alt+shift+#).

I think the best solution would be to let the user choose between the two (at least on Windows).

**Comment by gsomoza** [comment]
Thanks for your feedback, and I'm glad you're finding the plugin useful!

I'd love to be able to offer users the ability to choose their own key combinations, but unfortunately right now Firefox doesn't allow that. I'm afraid we'll have to wait until they allow their users to customise key-bindings natively..

The only alternative is to bind our commands to more than one key combination and then use settings to trigger the action only on the combination the user prefers. However doing that means not only much more complexity on the code, but also that we'd be "stealing" key combination possibilities for other plugins (TBH I don't know how Firefox handles that kind of conflict right now but whatever they're doing I can't imagine it results in good UX).

If anyone knows a viable workaround then I'd be happy to merge a PR.
