### ISSUE TITLE
Suggestion: similar shortcuts for "new window"?

### ISSUE THREAD

**Issue by scottbilas** [gsomoza/firefox-easy-container-shortcuts#4]
It sure would be nice to get a similar set of shortcuts for when creating a new window, instead of just a new tab. Would save a bit of extra hotkeying when opening a new window.

Current: Ctrl-N + Ctrl-Shift-# + Ctrl-Tab + Ctrl-W
Suggested: Ctrl-Shift-Alt-#

**Comment by gsomoza** [comment]
Nice suggestion, thanks! I might take it up. 

(But what would be even better is if you submit a PR for it: if you're a developer it's probably going to be easier than you might think :) interested?)

**Comment by gsomoza** [comment]
FYI the suggested shortcut of <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>Alt</kbd><kbd>#</kbd> is not supported by Firefox out of the box right now. Just to keep that in mind in case anyone wants to implement it.
