### ISSUE TITLE
Suggestion: make ctrl + G open a container of the same type as the open one

### ISSUE THREAD

**Issue by tasn** [gsomoza/firefox-easy-container-shortcuts#5]
This is an often requested feature (see https://github.com/mozilla/multi-account-containers/issues/462) and it shouldn't be too hard to do.

P.S, thanks a lot for this extension. Life changer!

**Comment by gsomoza** [comment]
Nice suggestion. Just tagged a new release that adds the feature – only that it does so with `Alt+T` so that it's similar to `Ctrl+T`.

**Comment by tasn** [comment]
Awesome, thanks! This is going to be life changing!

Maybe consider also making a comment on the aforementioned bug report, the readme and in the add-on's release page so more people know about it, if you haven't already.

**Comment by tasn** [comment]
I just updated the add-no and unfortunately it doesn't work here on Linux with FF 65.0.1. :(
It instead opens the "tools" menubar menu.

**Comment by fad1** [comment]
> 
> 
> I just updated the add-no and unfortunately it doesn't work here on Linux with FF 65.0.1. :(
> It instead opens the "tools" menubar menu.

Same thing, Alt+T opens menu bar Tools menu.

**Comment by gsomoza** [comment]
I can change the shortcut to something else only on Linux. Would `Alt+Shift+T` work on Linux? Otherwise I'll map it to Ctrl+G like you suggested.

**Comment by tasn** [comment]
`Alt + Shift + T` is a bit too cumbersome if you ask me. I chose `Ctrl + G` because G is next to T and seems to be mapped to search (search backwards maybe?) which is redundant. I don't know if such a clash would make it not work though... I can happily test whatever you want, just let me know how.

**Comment by gsomoza** [comment]
A test would be awesome, cause I don't have Linux or the time to setup a VM to test this. It should actually be quite easy:

1. Download this repository into a local folder.
2. On the manifest.json file, change the shortcut for the first action to whatever you'd like it to be. Not everything is supported, but feel free to experiment a bit if necessary.
3. To test the changes, visit a new tab and type `about:debugging` in the URL box. This will open a special page. 
5. Click "Load Temporary Add-on..." and select any file in the folder (e.g. you can select `manifest.json`). This will load the local version of the add-on with your changes.
6. You can still make changes to files and click on "reload" under that same debugging tab to test them.
7. Once you're happy let me know what key combo worked and I'll add it as a linux-only shortcut. Or if you're technical and know how to use Git, you can also submit a pull-request with your changes. That would be amazing.

The docs for the section of `manifest.json` that you'd be experimenting with are here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands

**Comment by tasn** [comment]
I can create a PR, no problem. Just a thought though: maybe let's make it Ctrl+Alt+T for all the platforms instead of an exception for Linux, what are your thoughts on that?
Alt+Shift is also a no-go, because it's commonly mapped as a language switcher (on Windows and commonly on Linux) and anyhow, it doesn't work on Firefox on Linux.

**Comment by gsomoza** [comment]
I personally don't mind completely different mappings for different OS's because sometimes it's just hard to avoid. But if a given combination has no issues on any OS then that's definitely better indeed.

Ctrl+Alt+T would be an issue for me on OSx because it's mapped to a popular window management tool. So for OSx we could do Cmd+Alt+T while for Windows and Linux we keep Ctrl+Alt+T. Mac users are more used to using Cmd than Ctrl anyways.

Are you (or anyone on this thread) able to test Ctrl+Alt+T on Windows? 

To be fair I didn't test Alt+Shift+T on Windows either so if this latest suggestion works on Linux and Mac then we might as well just go for it.

**Comment by tasn** [comment]
As said, Alt+Shift would be a problem on Windows too for multi-lingual users, as it's the default language switcher (yeah, using to modifiers is crazy, but that's how it has always been), so I think a no go anyway.
I can't test on Windows unfortunately
As for using Cmd on Macs: it's actually not an exception. Per your link, "Ctrl+Alt+T" is interpreted as "Cmd+Alt+T" on Macs, so that would be automatic.
Will open a PR now.

**Comment by tasn** [comment]
Awesome, thanks!

Please also release a new version when you have the time so we can actually use it. :)

Thanks again for this extension. It's life-changing! \o/

**Comment by gsomoza** [comment]
Glad the extension helped you as much as it helped me. Thanks so much for the PR!

I tagged a new version in this repo, but for some reason the Mozilla Developer Hub is not working properly so I can't submit the new version for publishing... I'll do that as soon as they fix it. 

Meanwhile I guess you can use the latest version by using the same procedure as described above.

**Comment by tasn** [comment]
I am already, it wasn't only for me, but for everyone. :)
