### ISSUE TITLE
reload current tab in different container

### ISSUE THREAD

**Issue by salarkhan** [gsomoza/firefox-easy-container-shortcuts#8]
pretty self explanatory. would be lovely!

**Comment by gsomoza** [comment]
It should definitely be possible to do it like this (all of the below would happen automatically when you trigger the key combo):

1. Open a new tab on current URL
2. Close current tab

I'm quite sure it can be accomplished like that, but the user experience might be quirky: the new tab will probably appear as the last tab in the window, which could be confusing if you're trying to switch on e.g. the first tab.

Of course the best solution is to replace the container in the existing tab, but it might be tricky to do that.

I'm tagging this issue as an "enhancement" and "help wanted". Anyone willing to contribute is welcome!
