### ISSUE TITLE
Suggestion: Set default container to open links from outside of Firefox

### ISSUE THREAD

**Issue by compiaffe** [gsomoza/firefox-easy-container-shortcuts#9]
It would be great if one could easily set or change the default container that is being used when opening a link from outside of Firefox.

So if one get's a message in a chat application (Slack, Telegram, etc) open a tab in the currently selected default container.

Maybe even have a keyboard shortcut to change the default container.

**Comment by gsomoza** [comment]
This would be indeed great. However I think it will be hard to implement properly as I don't think the Firefox API gives us enough tools to do that. I'll leave this ticket open because it would be a great feature, but it's unlikely it will get implemented until the API matures a bit more..

**Comment by jounathaen** [comment]
Maybe https://addons.mozilla.org/en-US/firefox/addon/conex/?src=search is what you want? It shows a selection dialouge when you open external links

**Comment by gsomoza** [comment]
Closing as an alternative has been suggested.
